name: linux

on: workflow_dispatch

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Build c-shared library for Linux (.so)
        run: |
          cd lib/gvm
          go build -buildmode=c-shared -o gvm_linux.so
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: dev-linux
          artifacts: gvm_linux.so
          prerelease: true
