name: linux

on: workflow_dispatch

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Build rsagg
        run: |
          cd rsagg
          cargo build --release
      - name: Build miner
        run: |
          go build -o cypa-miner cmd/gvm/main.go
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: dev-linux
          artifacts: cypa-miner
          prerelease: true
