name: windows

on: workflow_dispatch

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Build c-shared library for Windows (.dll)
        run: |
          cd lib/gvm
          go build -buildmode=c-shared -o ../../gvm_windows.dll
