name: windows

on: workflow_dispatch

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable-gnu
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git unzip mingw-w64-ucrt-x86_64-gc      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Build rsagg
        run: |
          cd rsagg
          cargo build --release
      - name: Build miner
        run: |
          go build -o cypa-miner.exe cmd/gvm/main.go
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: dev-windows
          artifacts: cypa-miner.exe
          prerelease: true
